# values.yaml
postgresql:
  nameOverride: postgres
  image:
    repository: postgres
    containerPort: 5432
  
  secretRef: postgres-secrets

  replicaCount: 1
  
  service:
    type: NodePort
    port: 5432