# values.yaml
postgresql:
  nameOverride: postgres
  image:
    repository: postgres
    containerPort: 5432
  
  secretRef: postgres-secrets

  replicaCount: 1

  tailscale: 
    status: true 
    
  # Dans votre values.yaml ou via un fichier service.yaml
  service:
    type: LoadBalancer
    port: 5432

  # Variables d'environnement
  env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: dagster-postgresql-secret
          key: POSTGRES_USER
          optional: false
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dagster-postgresql-secret
          key: POSTGRES_PASSWORD
          optional: false
    - name: POSTGRES_DB
      valueFrom:
        secretKeyRef:
          name: dagster-postgresql-secret
          key: POSTGRES_DB
          optional: false
        
